all:compile

compile: FORCE
	gcc *.c -o ultracp 
clean: FORCE
	rm ultracp
test: FORCE
	./ultracp src autre
zip:
	zip TP3SI_Hategekimana_Fabrice  Makefile *.c *.h TP3SI_Hategekimana_Fabrice.pdf

FORCE:
