
COURS=an
all: task
 
revisions: FORCE
	cd ~/cours/an/revisions
exercices: FORCE
	cd ~/cours/an/exercices
tps: FORCE
	cd ~/cours/an/tps
addtask: FORCE
	task add $(ARGS)$(SUB) $(COURS)
summary: FORCE
	task $(COURS) summary
task: FORCE
	task $(COURS)$(SUB)
FORCE:

